services:
  db:
    image: postgres:16.4
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tsr-server-manager
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  server:
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
      - DB_HOST=db
    ports:
      - 3000:3000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
      - /workspace/node_modules
      - /workspace/client/node_modules
      - /workspace/server/node_modules
  client:
    restart: always
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - ./:/workspace
      - /workspace/node_modules
      - /workspace/client/node_modules
      - /workspace/server/node_modules
    ports:
      - 3001:3001/tcp
    depends_on:
      - server
